[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
crewly_bounty = "4jcrRV3ab8boiXDF6YHdmRu9YwMLzonjuAK9pFSyFZPF"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
