-- drafts crewly writes for people to send themselves or through the app

create table public.draft (
  id bigint generated by default as identity primary key,
  company_id text not null default public.my_company() references public.company,
  kind text not null check (kind in ('email')),
  recipient jsonb not null default '{}',  -- {company_id, name, email}
  subject text not null check (length(subject) <= 300),
  body text not null check (length(body) <= 20000),
  attachments jsonb not null default '[]',  -- [{name, content_type, content}]
  about jsonb not null default '{}',  -- what it is about: {overlap_id | plan | request_id}
  status text not null default 'draft' check (status in ('draft', 'sent', 'copied')),
  sent_at timestamptz,
  created_by uuid not null default auth.uid() references auth.users on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index draft_company_idx on public.draft (company_id, created_at desc);

alter table public.draft enable row level security;

create policy "companies read their drafts" on public.draft for select to authenticated using (company_id = public.my_company());
create policy "people write their company's drafts" on public.draft for insert to authenticated
  with check (company_id = public.my_company() and created_by = auth.uid());
create policy "companies edit their drafts" on public.draft for update to authenticated
  using (company_id = public.my_company()) with check (company_id = public.my_company());
create policy "companies drop their drafts" on public.draft for delete to authenticated using (company_id = public.my_company());
